verficacionCodigoEstatico
LeslT/workshop-api-testing-js pull request #6
Opened 2019-08-30 13:54 UTC by LeslT

2019-08-30 13:55 UTC, holgiosalos requested changes

2019-08-30 13:55 UTC, holgiosalos commented on .eslintrc.yml
> +  "no-unused-expressions": "off"
agrega una linea vacia al final del archivo

2019-09-02 16:24 UTC, holgiosalos requested changes
Elimina la linea vacia del inicio del archivo y agrega una completamente vacia (sin espacios) al final del archivo

2019-09-03 16:49 UTC, holgiosalos approved these changes

2019-09-03 16:50 UTC, leonleo997 commented on test/MyFirstApiConsume.test.js
> +    // expect(response.body.args).to.eql(body);
delete comment

2019-09-03 16:50 UTC, leonleo997 commented on test/MyFirstApiConsume.test.js
> +    // console.log(response);
delete comment

2019-09-03 16:50 UTC, merged

2019-09-03 16:51 UTC, leonleo997 commented on test/MyFirstApiConsume.test.js
> +    // console.log(response);
delete comment